### ISSUE TITLE
Error loading psycopg2 module: No module named 'psycopg2'

### ISSUE THREAD

**Issue by merveminadursun** [merveminadursun/SWE573_2018719048_MinaOgur#7]
I changed my settings.py :

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'USER': 'postgres',
        'NAME': 'password',
        'TEST': {
            'NAME': 'communitydb',
        },
    },
}

```

Then I run `python manage.py migrate`

And I got following error:

```
Traceback (most recent call last):
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\backends\postgresql\base.py", line 20, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\VKT-MINAD\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\backends\postgresql\base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
```

**Comment by merveminadursun** [comment]
Download whl file from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/) under "**Psycopg, a PostgreSQL database adapter.**" title. Go to directroy of where the file is. then `pip install psycopg2-2.6.1-cp35-none-win32.whl` and the installation was successful.
